version: "2.1"
  
services:

  swx-web-db:
    container_name: swx-web-db
    hostname: swx-web-db
    image: mariadb/server:latest
    expose:
      - "3306"

  swx-web-server:
    container_name: swx-web-server
    hostname: swx-web-server
    build: .
    image: sofwerx/swx-web-server:latest
    expose:
      - "9000"
      - "443"

